package simu.entity;

import jakarta.persistence.*;

/**
 * JPA entity representing a single simulation run's line/station counts.
 * The entity is mapped to table {@code run}. The primary key {@link #id} is generated using
 * {@link GenerationType#IDENTITY} and will be {@code null} until the instance is persisted.
 * All other fields are non-null integer counters describing how many lines/servers a run uses
 * for each processing stage (check-in, luggage drop, security, passport control, and gate).
 * @author Elias Rinne
 */

@Entity
@Table(name = "run")
public class Run {

    /**
     * Surrogate primary key generated by the database (IDENTITY strategy).
     * Will be {@code null} until the entity has been persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /** Number of check-in queues/servers configured for this run. */
    @Column(name = "check_in_queues_count", nullable = false)
    private int checkInQueuesCount;

    /** Number of standard luggage-drop lines configured for this run. */
    @Column(name = "luggage_drop_count", nullable = false)
    private int luggageDropCount;

    /** Number of priority luggage-drop lines configured for this run. */
    @Column(name = "priority_luggage_drop_count", nullable = false)
    private int priorityLuggageDropCount;

    /** Number of standard security lines configured for this run. */
    @Column(name = "security_count", nullable = false)
    private int securityCount;

    /** Number of priority security lines configured for this run. */
    @Column(name = "priority_security_count", nullable = false)
    private int prioritySecurityCount;

    /** Number of passport control lines configured for this run. */
    @Column(name = "passport_control_count", nullable = false)
    private int passportControlCount;

    /** Number of priority passport control lines configured for this run. */
    @Column(name = "priority_passport_control_count", nullable = false)
    private int priorityPassportControlCount;

    /** Number of gate lines configured for this run. */
    @Column(name = "gate_count", nullable = false)
    private int gateCount;

    /**
     * Constructs a new {@code Run} with explicit counts for each station/line category.
     *
     * @param luggageDropCount number of standard luggage-drop lines
     * @param priorityLuggageDropCount number of priority luggage-drop lines
     * @param securityCount number of standard security lines
     * @param checkInQueuesCount number of check-in queues/servers
     * @param prioritySecurityCount number of priority security lines
     * @param passportControlCount number of passport control lines
     * @param priorityPassportControlCount number of priority passport control lines
     * @param gateCount number of gates
     *
     * @author Elias Rinne
     */
    public Run(int luggageDropCount, int priorityLuggageDropCount, int securityCount, int checkInQueuesCount, int prioritySecurityCount, int passportControlCount, int priorityPassportControlCount, int gateCount) {
        this.luggageDropCount = luggageDropCount;
        this.priorityLuggageDropCount = priorityLuggageDropCount;
        this.securityCount = securityCount;
        this.checkInQueuesCount = checkInQueuesCount;
        this.prioritySecurityCount = prioritySecurityCount;
        this.passportControlCount = passportControlCount;
        this.priorityPassportControlCount = priorityPassportControlCount;
        this.gateCount = gateCount;
    }

    /**
     * JPA-required no-arg constructor.
     * Used by the persistence provider to instantiate the entity via reflection.
     */
    public Run() {}

    /**
     * Returns the database-generated identifier.
     *
     * @return primary key value, or {@code null} if the entity has not been persisted yet
     */
    public Integer getId() {
        return id;
    }

    /**
     * Returns the number of check-in queues/servers configured for this run.
     *
     * @return check-in line count
     */
    public int getCheckInQueuesCount() {
        return checkInQueuesCount;
    }

    /**
     * Returns the number of standard luggage-drop lines configured for this run.
     *
     * @return standard luggage-drop line count
     */
    public int getLuggageDropCount() {
        return luggageDropCount;
    }

    /**
     * Returns the number of priority luggage-drop lines configured for this run.
     *
     * @return priority luggage-drop line count
     */
    public int getPriorityLuggageDropCount() {
        return priorityLuggageDropCount;
    }

    /**
     * Returns the number of standard security lines configured for this run.
     *
     * @return standard security line count
     */
    public int getSecurityCount() {
        return securityCount;
    }

    /**
     * Returns the number of priority security lines configured for this run.
     *
     * @return priority security line count
     */
    public int getPrioritySecurityCount() {
        return prioritySecurityCount;
    }

    /**
     * Returns the number of passport control lines configured for this run.
     *
     * @return passport control line count
     */
    public int getPassportControlCount() {
        return passportControlCount;
    }

    /**
     * Returns the number of priority passport control lines configured for this run.
     *
     * @return priority passport control line count
     */
    public int getPriorityPassportControlCount() {
        return priorityPassportControlCount;
    }

    /**
     * Returns the number of gate lines configured for this run.
     *
     * @return gate line count
     */
    public int getGateCount() {
        return gateCount;
    }

}
